# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('ADMIN', 'Admin'),
                    ('TEACHER', 'Teacher'),
                    ('STUDENT', 'Student'),
                ],
                default='STUDENT',
                max_length=20,
            ),
        ),
    ]
