# Generated by Django 6.0.5 on 2026-05-23 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('transmuted_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=120)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='subjects.subject')),
            ],
            options={
                'ordering': ['subject__code', 'student__username'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'student'), name='unique_final_grade_per_subject_student')],
            },
        ),
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('ACTIVITY', 'Activity'), ('ATTENDANCE', 'Attendance'), ('CODING', 'Coding'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Percentage weight in the final grade.', max_digits=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_categories', to='subjects.subject')),
            ],
            options={
                'verbose_name_plural': 'grade categories',
                'constraints': [models.UniqueConstraint(fields=('subject', 'category', 'name'), name='unique_subject_grade_category')],
            },
        ),
    ]
