# Generated by Django 6.0.5 on 2026-05-23 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradingTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_period', models.CharField(choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('PREFINAL', 'Prefinal'), ('FINAL', 'Final')], max_length=20)),
                ('category', models.CharField(choices=[('QUIZ', 'Quiz'), ('EXAM', 'Exam'), ('ACTIVITY', 'Activity'), ('ATTENDANCE', 'Attendance'), ('CODING', 'Coding'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Percentage weight inside this grading period.', max_digits=5)),
            ],
            options={
                'ordering': ['template', 'grading_period', 'category'],
            },
        ),
        migrations.CreateModel(
            name='PeriodGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_period', models.CharField(choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('PREFINAL', 'Prefinal'), ('FINAL', 'Final')], max_length=20)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remarks', models.CharField(blank=True, max_length=120)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject__code', 'grading_period', 'student__username'],
            },
        ),
        migrations.CreateModel(
            name='StudentCategoryGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('transmuted_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['subject__code', 'grade_category__grading_period', 'student__username'],
            },
        ),
        migrations.AlterModelOptions(
            name='gradecategory',
            options={'ordering': ['subject__code', 'grading_period', 'category'], 'verbose_name_plural': 'grade categories'},
        ),
        migrations.RemoveConstraint(
            model_name='gradecategory',
            name='unique_subject_grade_category',
        ),
        migrations.RemoveField(
            model_name='finalgrade',
            name='raw_score',
        ),
        migrations.RemoveField(
            model_name='finalgrade',
            name='transmuted_grade',
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='final_period_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='midterm_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='prefinal_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='prelim_grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='gradecategory',
            name='grading_period',
            field=models.CharField(choices=[('PRELIM', 'Prelim'), ('MIDTERM', 'Midterm'), ('PREFINAL', 'Prefinal'), ('FINAL', 'Final')], default='PRELIM', max_length=20),
        ),
        migrations.AlterField(
            model_name='gradecategory',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Percentage weight inside this grading period.', max_digits=5),
        ),
        migrations.AddField(
            model_name='gradingtemplateitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grades.gradingtemplate'),
        ),
        migrations.AddField(
            model_name='gradecategory',
            name='template_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_categories', to='grades.gradingtemplateitem'),
        ),
        migrations.AddConstraint(
            model_name='gradecategory',
            constraint=models.UniqueConstraint(fields=('subject', 'grading_period', 'category', 'name'), name='unique_subject_period_grade_category'),
        ),
        migrations.AddField(
            model_name='periodgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periodgrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_grades', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='studentcategorygrade',
            name='grade_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grades', to='grades.gradecategory'),
        ),
        migrations.AddField(
            model_name='studentcategorygrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcategorygrade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_category_grades', to='subjects.subject'),
        ),
        migrations.AddConstraint(
            model_name='gradingtemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'grading_period', 'category', 'name'), name='unique_template_period_category'),
        ),
        migrations.AddConstraint(
            model_name='periodgrade',
            constraint=models.UniqueConstraint(fields=('subject', 'student', 'grading_period'), name='unique_period_grade_per_subject_student'),
        ),
        migrations.AddConstraint(
            model_name='studentcategorygrade',
            constraint=models.UniqueConstraint(fields=('student', 'grade_category'), name='unique_student_category_grade'),
        ),
    ]
