# Generated by Codex on 2026-06-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('attendance', '0001_initial'),
        ('coding', '0001_initial'),
        ('grades', '0002_gradingtemplate_gradingtemplateitem_periodgrade_and_more'),
        ('learning_modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcategorygrade',
            name='is_item_computed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('points_possible', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('ASSESSMENT', 'Assessment'), ('MODULE_ACTIVITY', 'Module activity'), ('ATTENDANCE', 'Attendance'), ('CODING', 'Coding')], default='MANUAL', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_items', to='assessments.assessment')),
                ('attendance_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_items', to='attendance.attendancesession')),
                ('coding_problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_items', to='coding.programmingproblem')),
                ('grade_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grades.gradecategory')),
                ('module_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_items', to='learning_modules.moduleactivity')),
            ],
            options={
                'ordering': ['grade_category__subject__code', 'grade_category__grading_period', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentGradeItemScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('remarks', models.CharField(blank=True, max_length=160)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('grade_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='grades.gradeitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_item_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['grade_item__grade_category__grading_period', 'grade_item__order', 'student__username'],
            },
        ),
        migrations.AddConstraint(
            model_name='studentgradeitemscore',
            constraint=models.UniqueConstraint(fields=('grade_item', 'student'), name='unique_student_grade_item_score'),
        ),
    ]
