# Generated by Django 6.0.5 on 2026-05-23 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveSmallIntegerField()),
                ('end_year', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYearSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('FIRST', '1st Semester'), ('SECOND', '2nd Semester'), ('SUMMER', 'Summer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-school_year__start_year', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='SubjectSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(help_text='Meeting days, for example MWF or TTH.', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('section', models.CharField(blank=True, max_length=80)),
                ('room', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['school_year_semester', 'subject__code', 'days', 'start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['school_year_semester', 'subject__code', 'student__username']},
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_subject_student_enrollment',
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(fields=('start_year', 'end_year'), name='unique_school_year_range'),
        ),
        migrations.AddField(
            model_name='schoolyearsemester',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='subjects.schoolyear'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_year_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='subjects.schoolyearsemester'),
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='school_year_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_schedules', to='subjects.schoolyearsemester'),
        ),
        migrations.AddField(
            model_name='subjectschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='subjects.subjectschedule'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('school_year_semester__isnull', False)), fields=('subject', 'student', 'school_year_semester'), name='unique_subject_student_term_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('school_year_semester__isnull', True)), fields=('subject', 'student'), name='unique_subject_student_without_term'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('student', 'schedule'), name='unique_student_schedule_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='schoolyearsemester',
            constraint=models.UniqueConstraint(fields=('school_year', 'semester'), name='unique_school_year_semester'),
        ),
        migrations.AddConstraint(
            model_name='subjectschedule',
            constraint=models.UniqueConstraint(fields=('subject', 'school_year_semester', 'days', 'start_time', 'end_time', 'section'), name='unique_subject_schedule_slot'),
        ),
    ]
