# Generated by Django 6.0.5 on 2026-05-23 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_scheduled_enrollments(apps, schema_editor):
    Enrollment = apps.get_model('subjects', 'Enrollment')
    ScheduleStudent = apps.get_model('subjects', 'ScheduleStudent')

    for enrollment in Enrollment.objects.exclude(schedule__isnull=True):
        ScheduleStudent.objects.get_or_create(
            schedule_id=enrollment.schedule_id,
            student_id=enrollment.student_id,
            defaults={
                'is_active': enrollment.is_active,
                'added_at': enrollment.enrolled_at,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_schoolyear_schoolyearsemester_subjectschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['schedule__school_year_semester', 'schedule__subject__code', 'student__username'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_subject_student_term_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_subject_student_without_term',
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_student_schedule_enrollment',
        ),
        migrations.AddField(
            model_name='schedulestudent',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='subjects.subjectschedule'),
        ),
        migrations.AddField(
            model_name='schedulestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(copy_scheduled_enrollments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='enrollment',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='school_year_semester',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='subject',
        ),
        migrations.AddConstraint(
            model_name='schedulestudent',
            constraint=models.UniqueConstraint(fields=('schedule', 'student'), name='unique_student_schedule_enrollment'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
