# Generated by Django 5.2.16 on 2026-09-10 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
        ('subjects', '0006_privacy_class_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True)),
                ('retention_days_after_term_close', models.PositiveIntegerField()),
                ('wording', models.TextField(max_length=4000)),
                ('approved_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_retention_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-approved_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TermClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_export_sha256', models.CharField(max_length=64)),
                ('official_transfer_reference', models.CharField(max_length=500)),
                ('transfer_verified_at', models.DateTimeField()),
                ('dpo_approved_at', models.DateTimeField()),
                ('purge_after', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dpo_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_term_closures', to=settings.AUTH_USER_MODEL)),
                ('retention_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_closures', to='privacy.retentionpolicy')),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_closure', to='subjects.schoolyearsemester')),
                ('transfer_verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_term_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurgeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('DRY_RUN', 'Dry run'), ('EXECUTE', 'Execute')], max_length=20)),
                ('result', models.CharField(choices=[('READY', 'Ready'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed')], max_length=20)),
                ('counts', models.JSONField(default=dict)),
                ('blockers', models.JSONField(default=list)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_purge_runs', to=settings.AUTH_USER_MODEL)),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purge_runs', to='privacy.termclosure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(max_length=2000)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True, max_length=2000)),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placed_legal_holds', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_legal_holds', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_holds', to='subjects.schoolyearsemester')),
            ],
            options={
                'ordering': ['-placed_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('term',), name='single_active_legal_hold_per_term')],
            },
        ),
        migrations.AddConstraint(
            model_name='retentionpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='single_active_retention_policy'),
        ),
    ]
