# Generated by Django 5.2.16 on 2026-09-10 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_retentionpolicy_termclosure_purgerun_legalhold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='termclosure',
            name='dpo_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='termclosure',
            name='dpo_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_term_closures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='termclosure',
            name='purge_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
