import { useCallback, useEffect, useState } from 'react'
import { asArray } from '../api'
import type { AuthedRequest, WorkspaceData } from '../app/types'
import { readJwtUserId } from '../services/session'
import type {
  ApiList,
  Answer,
  Assessment,
  AssessmentAttempt,
  AssessmentAttemptQuestion,
  AttendanceRecord,
  AttendanceSession,
  Badge,
  CodeBlankAnswer,
  Choice,
  CodeSubmission,
  FinalGrade,
  GradeCategory,
  GradeItem,
  GradingTemplate,
  GradingTemplateItem,
  LevelRule,
  Module,
  ModuleAccess,
  ModuleActivity,
  ModuleActivityAnswer,
  ModuleActivityAttempt,
  ModuleActivityMatchingPair,
  ModuleActivityQuestion,
  ModuleActivityQuestionChoice,
  ModuleActivitySubmission,
  ModuleLesson,
  ModuleLessonAsset,
  ModuleLessonExample,
  ModuleLessonProgress,
  ModuleProgress,
  ModuleTopic,
  ModuleTopicProgress,
  PeriodGrade,
  PointLedger,
  ProgrammingProblem,
  Question,
  ScheduleStudent,
  SchoolYear,
  SchoolYearSemester,
  StudentBadge,
  StudentCategoryGrade,
  StudentGradeItemScore,
  StudentProfile,
  Subject,
  SubjectSchedule,
  TestCase,
  User,
} from '../types'
import { toErrorMessage } from '../utils/format'

const emptyData: WorkspaceData = {
  users: [],
  currentUser: null,
  profiles: [],
  profile: null,
  subjects: [],
  schoolYears: [],
  terms: [],
  schedules: [],
  enrollments: [],
  modules: [],
  moduleTopics: [],
  moduleLessons: [],
  lessonAssets: [],
  lessonExamples: [],
  lessonProgress: [],
  moduleAccess: [],
  activities: [],
  activityQuestions: [],
  activityChoices: [],
  activityMatchingPairs: [],
  activityAttempts: [],
  activityAnswers: [],
  submissions: [],
  progress: [],
  topicProgress: [],
  problems: [],
  testCases: [],
  codeSubmissions: [],
  codeBlankAnswers: [],
  assessments: [],
  attempts: [],
  attemptQuestions: [],
  questions: [],
  choices: [],
  answers: [],
  attendanceSessions: [],
  attendanceRecords: [],
  gradingTemplates: [],
  gradingTemplateItems: [],
  gradeCategories: [],
  gradeItems: [],
  categoryGrades: [],
  gradeItemScores: [],
  periodGrades: [],
  finalGrades: [],
  points: [],
  badges: [],
  studentBadges: [],
  levels: [],
  loading: true,
  error: '',
}

export function useWorkspaceData(api: AuthedRequest, accessToken: string) {
  const [state, setState] = useState<WorkspaceData>(emptyData)

  const load = useCallback(async () => {
    const errors: string[] = []

    const [
      users,
      profiles,
      subjects,
      schoolYears,
      terms,
      schedules,
      enrollments,
      modules,
      moduleTopics,
      moduleLessons,
      lessonAssets,
      lessonExamples,
      lessonProgress,
      moduleAccess,
      activities,
      activityQuestions,
      activityChoices,
      activityMatchingPairs,
      activityAttempts,
      activityAnswers,
      submissions,
      progress,
      topicProgress,
      problems,
      testCases,
      codeSubmissions,
      codeBlankAnswers,
      assessments,
      attempts,
      attemptQuestions,
      questions,
      choices,
      answers,
      attendanceSessions,
      attendanceRecords,
      gradingTemplates,
      gradingTemplateItems,
      gradeCategories,
      gradeItems,
      categoryGrades,
      gradeItemScores,
      periodGrades,
      finalGrades,
      points,
      badges,
      studentBadges,
      levels,
    ] = await Promise.all([
      safeLoad<User>(api, '/accounts/users/', errors),
      safeLoad<StudentProfile>(api, '/accounts/students/', errors),
      safeLoad<Subject>(api, '/subjects/subjects/', errors),
      safeLoad<SchoolYear>(api, '/subjects/school-years/', errors),
      safeLoad<SchoolYearSemester>(
        api,
        '/subjects/school-year-semesters/',
        errors,
      ),
      safeLoad<SubjectSchedule>(api, '/subjects/subject-schedules/', errors),
      safeLoad<ScheduleStudent>(api, '/subjects/schedule-students/', errors),
      safeLoad<Module>(api, '/modules/modules/', errors),
      safeLoad<ModuleTopic>(api, '/modules/topics/', errors),
      safeLoad<ModuleLesson>(api, '/modules/lessons/', errors),
      safeLoad<ModuleLessonAsset>(api, '/modules/lesson-assets/', errors),
      safeLoad<ModuleLessonExample>(api, '/modules/lesson-examples/', errors),
      safeLoad<ModuleLessonProgress>(api, '/modules/lesson-progress/', errors),
      safeLoad<ModuleAccess>(api, '/modules/access/', errors),
      safeLoad<ModuleActivity>(api, '/modules/activities/', errors),
      safeLoad<ModuleActivityQuestion>(api, '/modules/activity-questions/', errors),
      safeLoad<ModuleActivityQuestionChoice>(api, '/modules/activity-choices/', errors),
      safeLoad<ModuleActivityMatchingPair>(api, '/modules/activity-matching-pairs/', errors),
      safeLoad<ModuleActivityAttempt>(api, '/modules/activity-attempts/', errors),
      safeLoad<ModuleActivityAnswer>(api, '/modules/activity-answers/', errors),
      safeLoad<ModuleActivitySubmission>(api, '/modules/submissions/', errors),
      safeLoad<ModuleProgress>(api, '/modules/progress/', errors),
      safeLoad<ModuleTopicProgress>(api, '/modules/topic-progress/', errors),
      safeLoad<ProgrammingProblem>(api, '/coding/problems/', errors),
      safeLoad<TestCase>(api, '/coding/test-cases/', errors),
      safeLoad<CodeSubmission>(api, '/coding/submissions/', errors),
      safeLoad<CodeBlankAnswer>(api, '/coding/blank-answers/', errors),
      safeLoad<Assessment>(api, '/assessments/assessments/', errors),
      safeLoad<AssessmentAttempt>(api, '/assessments/attempts/', errors),
      safeLoad<AssessmentAttemptQuestion>(
        api,
        '/assessments/attempt-questions/',
        errors,
      ),
      safeLoad<Question>(api, '/assessments/questions/', errors),
      safeLoad<Choice>(api, '/assessments/choices/', errors),
      safeLoad<Answer>(api, '/assessments/answers/', errors),
      safeLoad<AttendanceSession>(api, '/attendance/sessions/', errors),
      safeLoad<AttendanceRecord>(api, '/attendance/records/', errors),
      safeLoad<GradingTemplate>(api, '/grades/templates/', errors),
      safeLoad<GradingTemplateItem>(api, '/grades/template-items/', errors),
      safeLoad<GradeCategory>(api, '/grades/categories/', errors),
      safeLoad<GradeItem>(api, '/grades/items/', errors),
      safeLoad<StudentCategoryGrade>(api, '/grades/student-categories/', errors),
      safeLoad<StudentGradeItemScore>(api, '/grades/item-scores/', errors),
      safeLoad<PeriodGrade>(api, '/grades/periods/', errors),
      safeLoad<FinalGrade>(api, '/grades/finals/', errors),
      safeLoad<PointLedger>(api, '/gamification/points/', errors),
      safeLoad<Badge>(api, '/gamification/badges/', errors),
      safeLoad<StudentBadge>(api, '/gamification/student-badges/', errors),
      safeLoad<LevelRule>(api, '/gamification/levels/', errors),
    ])

    const userId = readJwtUserId(accessToken)
    const currentUser = users.find((user) => user.id === userId) ?? users[0] ?? null
    const profile =
      profiles.find((item) => item.user === currentUser?.id) ?? profiles[0] ?? null

    setState({
      users,
      currentUser,
      profiles,
      profile,
      subjects,
      schoolYears,
      terms,
      schedules,
      enrollments,
      modules,
      moduleTopics,
      moduleLessons,
      lessonAssets,
      lessonExamples,
      lessonProgress,
      moduleAccess,
      activities,
      activityQuestions,
      activityChoices,
      activityMatchingPairs,
      activityAttempts,
      activityAnswers,
      submissions,
      progress,
      topicProgress,
      problems,
      testCases,
      codeSubmissions,
      codeBlankAnswers,
      assessments,
      attempts,
      attemptQuestions,
      questions,
      choices,
      answers,
      attendanceSessions,
      attendanceRecords,
      gradingTemplates,
      gradingTemplateItems,
      gradeCategories,
      gradeItems,
      categoryGrades,
      gradeItemScores,
      periodGrades,
      finalGrades,
      points,
      badges,
      studentBadges,
      levels,
      loading: false,
      error: errors.slice(0, 3).join(' '),
    })
  }, [accessToken, api])

  useEffect(() => {
    const loadTimer = window.setTimeout(() => {
      void load()
    }, 0)

    return () => window.clearTimeout(loadTimer)
  }, [load])

  return { ...state, refresh: load }
}

async function safeLoad<T>(
  api: AuthedRequest,
  path: string,
  errors: string[],
) {
  try {
    return asArray(await api<ApiList<T>>(path))
  } catch (caughtError) {
    errors.push(`${path}: ${toErrorMessage(caughtError)}`)
    return []
  }
}
