# Generated by Django 6.0.5 on 2026-05-26 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
        ('learning_modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduleactivity',
            options={'ordering': ['module', 'order', 'id'], 'verbose_name_plural': 'module activities'},
        ),
        migrations.AddField(
            model_name='module',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='module_pdfs/'),
        ),
        migrations.AddField(
            model_name='moduleactivity',
            name='activity_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('FILE_UPLOAD', 'File Upload'), ('CODE_COMPLETE', 'Complete Coding'), ('CODE_FILL_BLANK', 'Fill in the Blank Coding')], default='TEXT', max_length=30),
        ),
        migrations.AddField(
            model_name='moduleactivity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moduleactivity',
            name='programming_problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_activities', to='coding.programmingproblem'),
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning_modules.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'module progress',
                'ordering': ['-started_at'],
                'constraints': [models.UniqueConstraint(fields=('module', 'student'), name='unique_module_progress')],
            },
        ),
    ]
