# Generated by Django 6.0.5 on 2026-06-23 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_modules', '0007_teacher_only_lesson_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modulelesson',
            name='enrichment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modulelesson',
            name='evidence_of_learning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modulelesson',
            name='remediation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moduletopic',
            name='enduring_understanding',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moduletopic',
            name='essential_question',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moduletopic',
            name='performance_task',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moduletopic',
            name='success_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moduletopic',
            name='values_focus',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ModuleLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_viewed_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='learning_modules.modulelesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'module lesson progress',
                'ordering': ['-last_viewed_at'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='unique_module_lesson_progress')],
            },
        ),
    ]
