# Generated by Codex on 2026-06-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('subjects', '0002_schoolyear_schoolyearsemester_subjectschedule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancesession',
            name='unique_attendance_session',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='school_year_semester',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attendance_sessions',
                to='subjects.schoolyearsemester',
            ),
        ),
        migrations.AddConstraint(
            model_name='attendancesession',
            constraint=models.UniqueConstraint(
                fields=('subject', 'school_year_semester', 'date', 'title'),
                name='unique_attendance_session_term',
            ),
        ),
    ]
