# Generated by Django 6.0.5 on 2026-05-26 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('prompt', models.TextField(blank=True)),
                ('expected_answer', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('points', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='coding.programmingproblem')),
            ],
            options={
                'ordering': ['problem', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodeBlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('points_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('blank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='coding.codeblank')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blank_answers', to='coding.codesubmission')),
            ],
            options={
                'ordering': ['submission', 'blank__order', 'blank__id'],
            },
        ),
        migrations.AddConstraint(
            model_name='codeblank',
            constraint=models.UniqueConstraint(fields=('problem', 'key'), name='unique_code_blank_key_per_problem'),
        ),
        migrations.AddConstraint(
            model_name='codeblankanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'blank'), name='unique_code_blank_answer_per_submission'),
        ),
    ]
